name: wrong_test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd 3-python-package-tnh-tnh-needs-help
          pip install -r .github/workflows/requirements.txt
          pip install -U pytest
          pip install -e .

      - name: Run wrong_test
        run: |
          python -m pytest
